name: mooCompleter
author: remram
category: Forms
tags: [widgets,interface,auto completer,keyboard]
docs: https://github.com/remram/ch.remram.mootools.mooCompleter/blob/master/README.md
demo: http://jsfiddle.net/remram/HrbeW/
current: 1.1